/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_instance_free: (a: number, b: number) => void;
export const __wbg_polyaid_free: (a: number, b: number) => void;
export const __wbg_get_polyaid_0: (a: number) => number;
export const __wbg_set_polyaid_0: (a: number, b: number) => void;
export const __wbg_get_polyaid_1: (a: number) => [number, number];
export const __wbg_set_polyaid_1: (a: number, b: number, c: number) => void;
export const instance_new: () => number;
export const instance_add_polygon: (a: number, b: number, c: number) => number;
export const instance_mod_polygon: (a: number, b: number, c: number, d: number) => void;
export const instance_del_polygon: (a: number, b: number) => [number, number];
export const instance_iou: (a: number, b: number, c: number) => [number, number, number];
export const instance_polygons_under_coord: (a: number, b: number) => number;
export const instance_intersection: (a: number, b: number, c: number) => [number, number, number, number];
export const instance_rand_convex_poly: (a: number, b: number, c: number) => number;
export const instance_serialize: (a: number) => [number, number, number, number];
export const instance_import_list: (a: number, b: number, c: number) => [number, number];
export const new_session: () => number;
export const deserialize_session: (a: number, b: number) => [number, number, number];
export const __wbg_coord2d_free: (a: number, b: number) => void;
export const __wbg_get_coord2d_0: (a: number) => number;
export const __wbg_set_coord2d_0: (a: number, b: number) => void;
export const __wbg_get_coord2d_1: (a: number) => number;
export const __wbg_set_coord2d_1: (a: number, b: number) => void;
export const is_convex: (a: number, b: number) => number;
export const coord2d_new: (a: number, b: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_start: () => void;
